# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pusher-client"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Logan Koester", "Phil Leggetter"]
  s.date = "2013-01-30"
  s.description = "Ruby client for consuming WebSockets from http://pusher.com"
  s.email = "logan@logankoester.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "certs/cacert.pem",
    "examples/hello_pusher.rb",
    "examples/hello_pusher_async.rb",
    "examples/hello_pusher_ssl.rb",
    "examples/subscribe_private.rb",
    "lib/pusher-client.rb",
    "lib/pusher-client/channel.rb",
    "lib/pusher-client/channels.rb",
    "lib/pusher-client/socket.rb",
    "lib/pusher-client/websocket.rb",
    "pusher-client.gemspec",
    "test/pusherclient_test.rb",
    "test/test.watchr",
    "test/teststrap.rb"
  ]
  s.homepage = "http://github.com/pusher/pusher-ruby-client"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby client for consuming WebSockets from http://pusher.com"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libwebsocket>, ["0.1.5"])
      s.add_runtime_dependency(%q<ruby-hmac>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.3.1"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
    else
      s.add_dependency(%q<libwebsocket>, ["0.1.5"])
      s.add_dependency(%q<ruby-hmac>, ["~> 0.4.0"])
      s.add_dependency(%q<addressable>, ["~> 2.3.1"])
      s.add_dependency(%q<bacon>, [">= 0"])
    end
  else
    s.add_dependency(%q<libwebsocket>, ["0.1.5"])
    s.add_dependency(%q<addressable>, ["~> 2.3.1"])
    s.add_dependency(%q<ruby-hmac>, ["~> 0.4.0"])
    s.add_dependency(%q<bacon>, [">= 0"])
  end
  
end

